# findAll
GET http://localhost:8089/employee


###
POST http://localhost:8089/employee?name=唐三藏&age=28&salary=2500
Accept: text/plain
Cache-Control: no-cache

###
GET http://localhost:8089/employee/findLessThan

###
GET http://localhost:8089/employee/findGreaterThan

###
GET http://localhost:8089/employee/findLessThanAndGreaterThan

###
GET http://localhost:8089/employee/sort

###
GET http://localhost:8089/employee/pageable

###
